---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-command-probe
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command:
        - /bin/sh
        - ec
        - sleep 30; touch /tmp/ready; sleep 600
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        initialDelaySeconds: 10
        periodSeconds: 5

