---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: project-1
spec:
  containers:
    - image: nginx
      name: web-server
      resources:
        limits:
          memory: "300Mi"
          cpu: "1"