---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: myvol
          configMap:
            name: indexcm
      containers:
        - name: ngnixcontainer
          image: nginx
          volumeMounts:
            - name: myvol
              mountPath: /usr/share/nginx/html
              readOnly: yes